name: pm_monitor
description: App para mantenimiento preventivo de equipos
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.0
  flutter_localizations:
    sdk: flutter

  # QR
  qr_flutter: ^4.1.0
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  qr_code_scanner: ^1.0.1

  # Networking
  http: ^1.1.0

  # Time
  timeago: ^3.6.1

  #pdf
  pdf: ^3.10.4
  printing: ^5.11.1

  # Image Picker
  image_picker: ^1.0.4

  # Permissions
  permission_handler: ^11.0.1

  # Notifications
  flutter_local_notifications: ^16.3.0

  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.1
  firebase_messaging: ^15.1.5
  firebase_storage: ^12.3.7

  # UI and Formatting
  intl: ^0.20.2
  table_calendar: ^3.0.9

  # State Management
  provider: ^6.1.1

  # UI
  cupertino_icons: ^1.0.2

  # Navigation
  go_router: ^12.1.3

  # Utils
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
