name: pm_monitor
description: App para mantenimiento preventivo de equipos
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.0
  flutter_localizations:
    sdk: flutter

  # QR
  qr_flutter: ^4.1.0
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  mobile_scanner: ^7.0.0

  # Maps — mobile
  google_maps_flutter: ^2.9.0
  # Maps — web
  google_maps_flutter_web: ^0.5.4

  # Time
  timeago: ^3.6.1

  # PDF
  pdf: ^3.10.4
  printing: ^5.11.1
  syncfusion_flutter_pdfviewer: ^31.1.19
  url_launcher: ^6.2.1

  # Networking
  http: ^1.1.0

  # Image Picker
  image_picker: ^1.0.4

  # File Picker
  file_picker: ^8.1.4

  # Permissions
  geolocator: ^11.0.0
  geocoding: ^2.1.1
  permission_handler: ^11.0.1

  # Notifications
  flutter_local_notifications: ^17.2.4

  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.1
  firebase_messaging: ^15.1.5
  firebase_storage: ^12.3.7

  # UI and Formatting
  intl: ^0.20.2
  table_calendar: ^3.0.9

  # State Management
  provider: ^6.1.1

  # UI
  cupertino_icons: ^1.0.2

  # Navigation
  go_router: ^12.1.3

  uuid: ^4.0.0

  # Utils
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/