// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmXYr6Ob1bF29ahSSdeRehAWW5Npid-Dw',
    appId: '1:39011928988:android:cf2095c890862f93699659',
    messagingSenderId: '39011928988',
    projectId: 'pm-monitor-system',
    storageBucket: 'pm-monitor-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2uKPt143Lv5KPr1rYXHONKXHvOSf3se4',
    appId: '1:39011928988:ios:b068421920cb399f699659',
    messagingSenderId: '39011928988',
    projectId: 'pm-monitor-system',
    storageBucket: 'pm-monitor-system.firebasestorage.app',
    iosBundleId: 'com.example.pmMonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2uKPt143Lv5KPr1rYXHONKXHvOSf3se4',
    appId: '1:39011928988:ios:b068421920cb399f699659',
    messagingSenderId: '39011928988',
    projectId: 'pm-monitor-system',
    storageBucket: 'pm-monitor-system.firebasestorage.app',
    iosBundleId: 'com.example.pmMonitor',
  );
}
